### ISSUE TITLE
Issue with bazel build of Haskell package math-functions

### ISSUE THREAD

**Issue by arshrestha** [FormationAI/hazel#18]
Following issue encountered on 

Ubuntu 16.04.4 LTS (Xenial Xerus)
GHC v8.2.2
Nix revision c33c5239f62b4855b14dc5b01dfa3e2a885cf9ca

```
➜  hazel git:(master) bazel build @haskell_math_functions//:all
Starting local Bazel server and connecting to it...
...........
/nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2
INFO: Analysed 27 targets (13 packages loaded).
INFO: Found 27 targets...
ERROR: /home/ashrestha/.cache/bazel/_bazel_ashrestha/98700ac0081e3d500e0bf543dde9b2b3/external/haskell_math_functions/BUILD:14:1: Compiling math-functions failed (Exit 1)
<command line>: can't load .so/.DLL for: bazel-out/k8-fastbuild/bin/external/haskell_primitive/libHSexternalZShaskellZUprimitiveZSprimitive-0.6.3.0-ghc8.2.2.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
INFO: Elapsed time: 33.870s, Critical Path: 17.93s
INFO: 81 processes, linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by mrkkrp** [comment]
See tweag/rules_haskell#250.

**Comment by judah** [comment]
@arshrestha can you confirm whether this is still the case with the latest version of platform-core (`bazel-mvp` branch)?

**Comment by arshrestha** [comment]
Still same issue

```
➜  platform-core git:(bazel-mvp) bazel build @haskell_math_functions//:all
Starting local Bazel server and connecting to it...
..........
/nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2
INFO: Analysed 27 targets (14 packages loaded).
INFO: Found 27 targets...
ERROR: /home/ashrestha/.cache/bazel/_bazel_ashrestha/6a2afa4ec02391a6aa52228c2b501f80/external/haskell_math_functions/BUILD:18:1: HaskellBuildLibrary @haskell_math_functions//:math-functions failed (Exit 1)
<command line>: can't load .so/.DLL for: bazel-out/k8-fastbuild/bin/external/haskell_primitive/libHSexternalZShaskellZUprimitiveZSprimitive-0.6.3.0-ghc8.2.2.so (libstdc++.so.6: cannot open shared object file: No such file or directory)
INFO: Elapsed time: 46.409s, Critical Path: 25.86s
INFO: 81 processes, linux-sandbox.
FAILED: Build did NOT complete successfully
```

```
➜  platform-core git:(bazel-mvp) ldd bazel-out/k8-fastbuild/bin/external/haskell_primitive/libHSexternalZShaskellZUprimitiveZSprimitive-0.6.3.0-ghc8.2.2.so
	linux-vdso.so.1 =>  (0x00007ffcba33f000)
	libm.so.6 => /nix/store/d54amiggq6bw23jw6mdsgamvs6v1g3bh-glibc-2.25-123/lib/libm.so.6 (0x00007f097aafe000)
	libexternal_Shaskell_Uprimitive_Sprimitive-cbits_libprimitive-cbits.so => /home/ashrestha/platform-core/bazel-out/k8-fastbuild/bin/external/haskell_primitive/../../../../../bazel-out/k8-fastbuild/bin/external/haskell_primitive/libexternal_Shaskell_Uprimitive_Sprimitive-cbits_libprimitive-cbits.so (0x00007f097b2b2000)
	libHStransformers-0.5.2.0-ghc8.2.2.so => /nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2/lib/ghc-8.2.2/transformers-0.5.2.0/libHStransformers-0.5.2.0-ghc8.2.2.so (0x00007f097a7f5000)
	libHSbase-4.10.1.0-ghc8.2.2.so => /nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2/lib/ghc-8.2.2/base-4.10.1.0/libHSbase-4.10.1.0-ghc8.2.2.so (0x00007f0979c2e000)
	libHSinteger-gmp-1.0.1.0-ghc8.2.2.so => /nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0-ghc8.2.2.so (0x00007f09799f3000)
	libHSghc-prim-0.5.1.1-ghc8.2.2.so => /nix/store/xjgn21ai9mg1ghfb1sb34wgarnpbcrzm-ghc-8.2.2/lib/ghc-8.2.2/ghc-prim-0.5.1.1/libHSghc-prim-0.5.1.1-ghc8.2.2.so (0x00007f0979357000)
	libgmp.so.10 => /nix/store/9q004jgdiqv9pziik3sxffbzwz49fgjn-gmp-6.1.2/lib/libgmp.so.10 (0x00007f09790c4000)
	libc.so.6 => /nix/store/d54amiggq6bw23jw6mdsgamvs6v1g3bh-glibc-2.25-123/lib/libc.so.6 (0x00007f0978d24000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f097b093000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f09789a2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f097878c000)
```

**Comment by judah** [comment]
I looked into this a little more.  For the purposes of Hazel, what we really want is to link a pure C library, not C++; that would work around this issue.  It looks like that's doable, but nontrivial: https://github.com/bazelbuild/bazel/issues/2954

**Comment by judah** [comment]
It looks like we might be able to work around this on affected machines by setting the environmental variable `BAZEL_LINKOPTS=""`.  Specifically, that prevents every `cc_library` from linking against `libstdc++`:
https://github.com/bazelbuild/bazel/commit/19c64284fb33372bd1a9185e0e8bb2a7b32265a1#diff-9899f9deb6047fe5ab4a4d2f8a96122e

@arshrestha or @nhibberd, can you confirm whether that fixes the build for you?

**Comment by arshrestha** [comment]
@judah it triggers bazel error

```
➜  platform-core git:(bazel-mvp) ✗ BAZEL_LINKOPTS="" bazel build @haskell_math_functions//:all
INFO: Analysed 27 targets (1 packages loaded).
INFO: Found 27 targets...
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636), actionIndex=4}' (requested by nodes 'external/haskell_primitive/libprimitive-cbits.so-2.params @haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636)')
INFO: Elapsed time: 1.453s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636), actionIndex=4}' (requested by nodes 'external/haskell_primitive/libprimitive-cbits.so-2.params @haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:424)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.extractArgumentsForDynamicLinkParamFile(LinkCommandLine.java:331)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.splitCommandline(LinkCommandLine.java:211)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.access$100(LinkCommandLine.java:45)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine$ParamFileCommandLine.arguments(LinkCommandLine.java:260)
	at com.google.devtools.build.lib.actions.CommandLine.addToFingerprint(CommandLine.java:57)
	at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction.computeKey(ParameterFileWriteAction.java:187)
	at com.google.devtools.build.lib.actions.AbstractAction.getKey(AbstractAction.java:322)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:310)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:269)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:501)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:366)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:194)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:347)
	... 4 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636), actionIndex=4}' (requested by nodes 'external/haskell_primitive/libprimitive-cbits.so-2.params @haskell_primitive//:primitive-cbits com.google.devtools.build.lib.skyframe.BuildConfigurationValue$Key@99896fcf false (1879157636)')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:424)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:355)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.extractArgumentsForDynamicLinkParamFile(LinkCommandLine.java:331)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.splitCommandline(LinkCommandLine.java:211)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine.access$100(LinkCommandLine.java:45)
	at com.google.devtools.build.lib.rules.cpp.LinkCommandLine$ParamFileCommandLine.arguments(LinkCommandLine.java:260)
	at com.google.devtools.build.lib.actions.CommandLine.addToFingerprint(CommandLine.java:57)
	at com.google.devtools.build.lib.analysis.actions.ParameterFileWriteAction.computeKey(ParameterFileWriteAction.java:187)
	at com.google.devtools.build.lib.actions.AbstractAction.getKey(AbstractAction.java:322)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.mustExecute(ActionCacheChecker.java:310)
	at com.google.devtools.build.lib.actions.ActionCacheChecker.getTokenIfNeedToExecute(ActionCacheChecker.java:269)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.checkActionCache(SkyframeActionExecutor.java:501)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:366)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:194)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:347)
	... 4 more
```

**Comment by nhibberd** [comment]
Same error for me

**Comment by judah** [comment]
Ah, sorry about that.  I was able to reproduce the failure in a docker container; this got it working for me:
```export BAZEL_LINKOPTS=-lm```

**Comment by judah** [comment]
Done as of #4113.
